### ISSUE TITLE
Teensy 3.2 Port

### ISSUE THREAD

**Issue by ReeceKetley** [ChrisBall/Dub-Siren-Files#3]
Hi, Greatwork with this i built and own a soundsystem which i want to use this with. However i'd like to use a Teensy 3.2 instead i've seen you'd already ported it to teensy so i assume its possible will you be releaseing the source code as im having issues porting myself. (specificly TC realted stuff)

**Comment by ChrisBall** [comment]
Hi Reece - I've hesistated to put this code up because I still sell these. It's easily possible to adapt the existing code for Teensy 3.2.
The main change is to change the TC handler (the main audio interrupt) from the DUE hardware timer to fire instead on the teensy's timer - you can use the timerOne library instead. You will also need to reduce the audio buffer size to fit in the Teensy's smaller SRAM.

I also added warmer distortion, a LP filter in the feedback loop, and some MIDI functions in the teensy version, but of course these aren't necessary.

Let me know if you're having trouble with that and I can give pointers! I would consider uploading a basic version of the code for teensy that doesn't have the above features.

**Comment by ReeceKetley** [comment]
Thank's for the reply i ended up writting my own from scratch and using an SRAM expansion to give me more memory for the delay. But i think ill move it to the 3.6 platform.

**Comment by ChrisBall** [comment]
Nice!
